services:
  - type: web
    name: qotil-bot-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn keep_alive:app & python3 main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
